"""add user admin flag

Revision ID: daa536b10fba
Revises: c1c89e0d4527
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'daa536b10fba'
down_revision: Union[str, None] = 'c1c89e0d4527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###